# This code is used to generate perfectly-looped video of ASCII art fade animation. 
# Mostly generated by AI, with some manual tweaks and overview
# Please ensure you have all dependencies listed below. 
# Quick command for pacman installation:

# sudo pacman -S python-pillow python-numpy python-imageio python-imageio-ffmpeg

# or use local environment to not install these packages system-wide.   
# I only checked and used this on my 3440x1440 monitor 
# so you might need to tweak some things until it works for you



from PIL import Image, ImageDraw, ImageFont, ImageFilter, ImageEnhance, ImageChops
import numpy as np
import imageio
import random

# ===== SETTINGS =====
WIDTH, HEIGHT = 3440, 1440
FPS = 170
DURATION = 10 # Video is perfectly looped, treat this as Period
OUTPUT_FILE = "bg.mp4"
ASCII_FILE = "ascii-art.txt"

# ASCII Positioning (Relative to upper-left corner)
POS_X_RATIO = 1.0
POS_Y_RATIO = 0.5

# Font parameters (Relevant only for logo in bg-video generation)
FONT_PATH = "DejaVuSansMono.ttf"
FONT_SIZE = 22
LINE_SPACING = 1.5

COLOR_PALETTE = [(0, 200, 255), (0, 255, 255), (0,255,170)]
NOISE_ZOOM = 0.2 #Scale for pallete. Lower scale-"key" color points are more spaced out

# Background and Glow
BACKGROUND_COLOR = (10, 10, 10)
BLUR_RADIUS = 90                     
GLOW_STRENGTH = 1.3 
GLOW_ADDITIVE = True    #switch between covering (additive) and opacity-based modes. Former gives more vibrant glow

# Animation parameters
MIN_STATE_DURATION = 1.0
MAX_STATE_DURATION = 4.0
MIN_FADE_DURATION = 0.2
MAX_FADE_DURATION = 0.8
NUM_TRANSITIONS_RANGE = (2, 8) # the amount of transitions every char 
                    #could go through in one period. Change together with DURATION

# ===== SETTINGS END =====






# ===== ASCII Loading =====
with open(ASCII_FILE, 'r', encoding='utf-8') as f:
    ascii_art = f.read().splitlines()

num_lines = len(ascii_art)
max_width_chars = max(len(line) for line in ascii_art) if ascii_art else 0

# ===== Font setup and positioning =====
font = ImageFont.truetype(FONT_PATH, FONT_SIZE)
bbox = font.getbbox("A")
char_w = bbox[2] - bbox[0]
char_h = bbox[3] - bbox[1]

step_y = char_h * LINE_SPACING
step_x = char_w

art_width_px = max_width_chars * step_x
art_height_px = num_lines * step_y
start_x = (WIDTH - art_width_px) * POS_X_RATIO
start_y = (HEIGHT - art_height_px) * POS_Y_RATIO

# ===== Color map generation =====
def generate_value_noise(width=128, height=128, tileable=True):
    grid = np.random.rand(height, width).astype(np.float32)
    if tileable:
        grid[-1, :] = grid[0, :]
        grid[:, -1] = grid[:, 0]
    return grid

def smoothstep(x):
    x = max(0.0, min(1.0, x))
    return x * x * (3 - 2 * x)

def sample_noise(noise_grid, x, y):
    h, w = noise_grid.shape
    x = x % 1.0
    y = y % 1.0
    x_scaled = x * (w - 1)
    y_scaled = y * (h - 1)
    x0 = int(x_scaled)
    y0 = int(y_scaled)
    x1 = (x0 + 1) % w
    y1 = (y0 + 1) % h
    fx = x_scaled - x0
    fy = y_scaled - y0
    sx = smoothstep(fx)
    sy = smoothstep(fy)
    v00 = noise_grid[y0, x0]
    v10 = noise_grid[y0, x1]
    v01 = noise_grid[y1, x0]
    v11 = noise_grid[y1, x1]
    v0 = v00 * (1 - sx) + v10 * sx
    v1 = v01 * (1 - sx) + v11 * sx
    return v0 * (1 - sy) + v1 * sy

def interpolate_color(palette, t):
    if len(palette) == 1:
        return palette[0]
    k = len(palette)
    segment = t * (k - 1)
    i = int(segment)
    if i >= k - 1:
        i = k - 2
        local_t = 1.0
    else:
        local_t = segment - i
    c1 = palette[i]
    c2 = palette[i+1]
    r = int(c1[0] * (1 - local_t) + c2[0] * local_t)
    g = int(c1[1] * (1 - local_t) + c2[1] * local_t)
    b = int(c1[2] * (1 - local_t) + c2[2] * local_t)
    return (r, g, b)

# One-time generation
if COLOR_PALETTE and len(COLOR_PALETTE) > 1:
    noise_grid = generate_value_noise()
else:
    noise_grid = None

def get_symbol_color(row_idx, col_idx, num_rows, num_cols):
    if not COLOR_PALETTE:
        return (255, 255, 255)
    if len(COLOR_PALETTE) == 1:
        return COLOR_PALETTE[0]
    nx = (col_idx / max(num_cols - 1, 1)) * NOISE_ZOOM
    ny = (row_idx / max(num_rows - 1, 1)) * NOISE_ZOOM
    noise_val = sample_noise(noise_grid, nx, ny)
    return interpolate_color(COLOR_PALETTE, noise_val)

# ===== Char Animation and Looping =====
def generate_symbol_segments(initial_alpha, num_transitions, duration,
                             min_state, max_state, min_fade, max_fade):
    if num_transitions % 2 != 0:
        num_transitions += 1
    if num_transitions < 2:
        num_transitions = 2

    total_segments = 2 * num_transitions
    durations = []
    types = []
    current_alpha = initial_alpha
    for i in range(total_segments):
        if i % 2 == 0:
            seg_type = 'transition'
            dur = random.uniform(min_fade, max_fade)
            to_alpha = 1 - current_alpha
        else:
            seg_type = 'hold'
            dur = random.uniform(min_state, max_state)
            to_alpha = current_alpha
        durations.append(dur)
        types.append(seg_type)
        current_alpha = to_alpha

    total = sum(durations)
    scale = duration / total
    scaled_durations = [d * scale for d in durations]

    segments = []
    current_time = 0.0
    current_alpha = initial_alpha
    for i, (dur, seg_type) in enumerate(zip(scaled_durations, types)):
        end_time = current_time + dur
        if i % 2 == 0:
            from_alpha = current_alpha
            to_alpha = 1 - current_alpha
        else:
            from_alpha = current_alpha
            to_alpha = current_alpha
        segments.append((current_time, end_time, seg_type, from_alpha, to_alpha))
        current_alpha = to_alpha
        current_time = end_time

    segments[-1] = (segments[-1][0], duration, segments[-1][2], segments[-1][3], segments[-1][4])
    return segments

def get_alpha_at_time(t, segments):
    for start, end, seg_type, from_a, to_a in segments:
        if start <= t <= end:
            if seg_type == 'hold':
                return from_a
            else:
                progress = (t - start) / (end - start) if end > start else 1.0
                eased = smoothstep(progress)
                return from_a + (to_a - from_a) * eased
        elif t < start:
            return segments[0][3]
    return segments[-1][4]

# ===== Char list assignment =====
symbols = []
for row_idx, line in enumerate(ascii_art):
    for col_idx, ch in enumerate(line):
        if ch == ' ':
            continue
        x = start_x + col_idx * step_x
        y = start_y + row_idx * step_y

        color = get_symbol_color(row_idx, col_idx, num_lines, max_width_chars)

        initial_alpha = random.choice([0.0, 1.0])
        min_trans, max_trans = NUM_TRANSITIONS_RANGE
        num_trans = random.randint(min_trans, max_trans)
        if num_trans % 2 != 0:
            num_trans += 1

        segments = generate_symbol_segments(
            initial_alpha, num_trans, DURATION,
            MIN_STATE_DURATION, MAX_STATE_DURATION,
            MIN_FADE_DURATION, MAX_FADE_DURATION
        )
        phase_offset = random.uniform(0, DURATION)

        symbols.append({
            'char': ch,
            'x': x,
            'y': y,
            'color': color,
            'segments': segments,
            'phase_offset': phase_offset,
        })

print(f"Chars Total: {len(symbols)}")

# ===== Video generation =====
total_frames = int(FPS * DURATION)
writer = imageio.get_writer(OUTPUT_FILE, fps=FPS, pixelformat="yuv420p10le", codec='libx265', quality=None, macro_block_size=1, output_params=["-crf", "1", "-preset", "slow"])

for frame_idx in range(total_frames):
    t = frame_idx / FPS

    # Background (Single plain color)
    background = Image.new('RGB', (WIDTH, HEIGHT), color=BACKGROUND_COLOR)

    # Transparent layer for chars
    symbol_layer = Image.new('RGBA', (WIDTH, HEIGHT), (0, 0, 0, 0))
    draw = ImageDraw.Draw(symbol_layer)

    for sym in symbols:
        t_shifted = (t + sym['phase_offset']) % DURATION
        alpha = get_alpha_at_time(t_shifted, sym['segments'])
        if alpha <= 0.01:
            continue
        r, g, b = sym['color']
        draw.text((sym['x'], sym['y']), sym['char'], font=font,
                  fill=(r, g, b, int(alpha * 255)))

    # Blur layer- chars from the previous step get blurred and put behind the main chars for glow effect
    glow_layer = symbol_layer.copy()
    glow_layer = glow_layer.filter(ImageFilter.GaussianBlur(BLUR_RADIUS))

    if GLOW_ADDITIVE:
        # convert to RGB (no alpha channel)
        glow_rgb = glow_layer.convert('RGB')
        # Increase brightness
        enhancer = ImageEnhance.Brightness(glow_rgb)
        glow_rgb = enhancer.enhance(GLOW_STRENGTH)
        # Add plain color image to "canvas" (background will hold all layers)
        background = ImageChops.add(background, glow_rgb)
    else:
        # Old method of adding glow, based on alpha channel
        glow_layer.putalpha(glow_layer.getchannel('A').point(lambda a: int(a * 1.0)))  # GLOW_ALPHA_MULTIPLIER = 1.0
        background.paste(glow_layer, (0, 0), glow_layer)

    background.paste(symbol_layer, (0, 0), symbol_layer)
    writer.append_data(np.array(background))

    if frame_idx % FPS == 0:
        print(f"Progress: {round(frame_idx/total_frames*100)}%")

writer.close()
print(f"Done! Video is saved to {OUTPUT_FILE}")